create-pages:
  image: registry.lujian.org/dev/mirrors/alpine:latest
  pages:
    publish: tools
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" registry.lujian.org
  script:
    - echo "hello world"
