create-pages:
  image: registry.lujian.org/open/mirrors/alpine:latest
  pages:
    publish: tools
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script: []
  script:
    - echo "hello world"
